sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2b1
loading pickled environment... done
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 5 changed, 0 removed
reading sources... [ 20%] index
reading sources... [ 40%] leo.core
reading sources... [ 60%] leo.external
reading sources... [ 80%] leo.external.concurrent.futures
reading sources... [100%] leo.plugins
Can not import path from plugin leo.plugins.at_view
Can not import win32clipboard from plugin leo.plugins.at_view
leo_pdf.py: can not import reportlab.platypus
Can not import Pmw from plugin tkGui
Can not import win32com.client
Can not import Ft from plugin leo.plugins.xsltWithNodes

/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/index.rst:10: WARNING: Title underline too short.

Welcome to Leo's API documentation!
===============================
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:4: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:26: WARNING: invalid signature for automodule (u'leo.core.format-code')
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:26: WARNING: don't know which module to import for autodocumenting u'leo.core.format-code' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoAtFile.py:docstring of leo.core.leoAtFile.atFile.replaceTargetFileIfDifferent:5: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoConfig.py:docstring of leo.core.leoConfig.GlobalConfigManager.config_iter:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:130: WARNING: autodoc: failed to import module u'leo.core.leoEditCommands'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoEditCommands.py", line 211, in <module>
    @g.command('open-url')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2747, in __call__
    g.error('@command decorator inside leoGlobals.py')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2870, in error
    g.es_print(color=g.actualColor('red'),*args,**keys)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2803, in actualColor
    if not g.app.log:
AttributeError: 'NoneType' object has no attribute 'log'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py:docstring of leo.core.leoGlobals.find_constants_defined:10: WARNING: Field list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py:docstring of leo.core.leoGlobals.os_path_finalize_join:1: WARNING: Inline emphasis start-string without end-string.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoIPython.py:docstring of leo.core.leoIPython.LeoWorkbook:8: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:186: WARNING: autodoc: failed to import module u'leo.core.leoImport'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoImport.py", line 5136, in <module>
    @g.command('parse-body')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2747, in __call__
    g.error('@command decorator inside leoGlobals.py')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2870, in error
    g.es_print(color=g.actualColor('red'),*args,**keys)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2803, in actualColor
    if not g.app.log:
AttributeError: 'NoneType' object has no attribute 'log'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoPlugins.py:docstring of leo.core.leoPlugins.baseLeoPlugin:3: ERROR: The "contents" directive may not be used within topics or body elements.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoPlugins.py:docstring of leo.core.leoPlugins.baseLeoPlugin:6: SEVERE: Unexpected section title.

Usage
=====
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoPlugins.py:docstring of leo.core.leoPlugins.baseLeoPlugin:10: SEVERE: Unexpected section title.

Initialization
--------------
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoPlugins.py:docstring of leo.core.leoPlugins.baseLeoPlugin:36: SEVERE: Unexpected section title.

Configuration
-------------
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoPlugins.py:docstring of leo.core.leoPlugins.baseLeoPlugin:66: SEVERE: Unexpected section title.

Example
=======
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoRst.py:docstring of leo.core.leoRst.link_htmlparserClass:4: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoRst.py:docstring of leo.core.leoRst.link_htmlparserClass.handle_starttag:4: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.core.rst:250: WARNING: autodoc: failed to import module u'leo.core.leoSessions'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoSessions.py", line 118, in <module>
    @g.command('session-clear')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2747, in __call__
    g.error('@command decorator inside leoGlobals.py')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2870, in error
    g.es_print(color=g.actualColor('red'),*args,**keys)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 2803, in actualColor
    if not g.app.log:
AttributeError: 'NoneType' object has no attribute 'log'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoShadow.py:docstring of leo.core.leoShadow.shadowController.propagate_changed_lines:8: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoShadow.py:docstring of leo.core.leoShadow.shadowController.propagate_changed_lines:9: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoShadow.py:docstring of leo.core.leoShadow.shadowController.strip_sentinels_with_map:8: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoTest.py:docstring of leo.core.leoTest.factorial:18: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoTest.py:docstring of leo.core.leoTest.factorial:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoTest.py:docstring of leo.core.leoTest.factorial:26: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoTest.py:docstring of leo.core.leoTest.factorial:27: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoRst.py:docstring of leo.core.leoRst:6: ERROR: Unknown target name: "docutils".
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoRst.py:docstring of leo.core.leoRst:6: ERROR: Unknown target name: "silvercity".
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.rst:4: WARNING: Explicit markup ends without a blank line; unexpected unindent.
docstring of leo.external.edb:101: ERROR: Unexpected indentation.
docstring of leo.external.edb:291: ERROR: Unexpected indentation.
docstring of leo.external.edb.Pdb.do_cl:3: ERROR: Unexpected indentation.
docstring of leo.external.edb.Pdb.do_clear:3: ERROR: Unexpected indentation.
docstring of leo.external.edb.Pdb.do_exit:3: ERROR: Unexpected indentation.
docstring of leo.external.edb.Pdb.do_q:3: ERROR: Unexpected indentation.
docstring of leo.external.edb.Pdb.do_quit:3: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.rst:34: WARNING: autodoc: failed to import module u'leo.external.ipy_leo'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/ipy_leo.py", line 22, in <module>
    import IPython.ipapi
ImportError: No module named IPython.ipapi
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.rst:42: WARNING: autodoc: failed to import module u'leo.external.leoSAGlobals'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/leoSAGlobals.py", line 17, in <module>
    import PyQt4.QtCore as QtCore
ImportError: No module named PyQt4.QtCore
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.rst:50: WARNING: autodoc: failed to import module u'leo.external.leoftsindex'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/leoftsindex.py", line 38, in <module>
    import leo.plugins.leofts as leofts
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leofts.py", line 1, in <module>
    import whoosh
ImportError: No module named whoosh
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.rst:66: WARNING: autodoc: failed to import module u'leo.external.lproto'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/lproto.py", line 16, in <module>
    from PyQt4 import QtCore, QtNetwork
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/stringlist.py:docstring of leo.external.stringlist.SList.fields:7: WARNING: Option list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:4: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:10: WARNING: autodoc: failed to import module u'leo.external.concurrent.futures'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
ImportError: No module named concurrent.futures._base
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:18: WARNING: autodoc: failed to import module u'leo.external.concurrent.futures._base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
ImportError: No module named concurrent.futures._base
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:26: WARNING: autodoc: failed to import module u'leo.external.concurrent.futures._compat'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
ImportError: No module named concurrent.futures._base
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:34: WARNING: autodoc: failed to import module u'leo.external.concurrent.futures.process'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
ImportError: No module named concurrent.futures._base
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.external.concurrent.futures.rst:42: WARNING: autodoc: failed to import module u'leo.external.concurrent.futures.thread'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
ImportError: No module named concurrent.futures._base
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:4: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:26: WARNING: autodoc: failed to import module u'leo.plugins.active_path'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/active_path.py", line 105, in <module>
    if g.app.gui.guiName() == "qt":
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:66: WARNING: autodoc: failed to import module u'leo.plugins.attrib_edit'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/attrib_edit.py", line 113, in <module>
    if g.app.gui.guiName() == "qt":
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:74: WARNING: autodoc: failed to import module u'leo.plugins.backlink'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/backlink.py", line 88, in <module>
    if g.app.gui.guiName() == "tkinter":
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:82: WARNING: autodoc: failed to import module u'leo.plugins.baseNativeTree'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/baseNativeTree.py", line 19, in <module>
    import PyQt4.QtGui as QtGui
ImportError: No module named PyQt4.QtGui
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/bibtex.py:docstring of leo.plugins.bibtex.readBibTexFileIntoTree:4: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:98: WARNING: autodoc: failed to import module u'leo.plugins.bigdash'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/bigdash.py", line 38, in <module>
    from PyQt4.QtCore import *
ImportError: No module named PyQt4.QtCore
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:106: WARNING: autodoc: failed to import module u'leo.plugins.bookmarks'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/bookmarks.py", line 59, in <module>
    if g.app.gui.guiName() == 'qt':
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:114: WARNING: autodoc: failed to import module u'leo.plugins.bzr_qcommands'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/bzr_qcommands.py", line 18, in <module>
    from PyQt4 import QtCore
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:146: WARNING: autodoc: failed to import module u'leo.plugins.contextmenu'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/contextmenu.py", line 58, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:154: WARNING: autodoc: failed to import module u'leo.plugins.ctagscompleter'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/ctagscompleter.py", line 44, in <module>
    from PyQt4.QtGui import QCompleter
ImportError: No module named PyQt4.QtGui
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:186: WARNING: autodoc: failed to import module u'leo.plugins.dragdropgoodies'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/dragdropgoodies.py", line 29, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:234: WARNING: autodoc: failed to import module u'leo.plugins.free_layout'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/free_layout.py", line 24, in <module>
    from PyQt4 import QtCore, QtGui, Qt
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:242: WARNING: autodoc: failed to import module u'leo.plugins.ftp'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/ftp.py", line 24, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:266: WARNING: autodoc: failed to import module u'leo.plugins.graphcanvas'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/graphcanvas.py", line 54, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:274: WARNING: autodoc: failed to import module u'leo.plugins.gtkDialogs'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/gtkDialogs.py", line 49, in <module>
    import leoGlobals as g
ImportError: No module named leoGlobals
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:282: WARNING: autodoc: failed to import module u'leo.plugins.gtkGui'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/gtkGui.py", line 5, in <module>
    import leoGlobals as g
ImportError: No module named leoGlobals
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:306: WARNING: autodoc: failed to import module u'leo.plugins.interact'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/interact.py", line 45, in <module>
    import pexpect
ImportError: No module named pexpect
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:314: WARNING: autodoc: failed to import module u'leo.plugins.internal_ipkernel'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/internal_ipkernel.py", line 8, in <module>
    from IPython.lib.kernel import connect_qtconsole
ImportError: No module named IPython.lib.kernel
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:330: WARNING: autodoc: failed to import module u'leo.plugins.ironPythonGui'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/ironPythonGui.py", line 24, in <module>
    import System
ImportError: No module named System
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:362: WARNING: autodoc: failed to import module u'leo.plugins.leo_pdf'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leo_pdf.py", line 275, in <module>
    import reportlab.platypus
ImportError: No module named reportlab.platypus
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:402: WARNING: autodoc: failed to import module u'leo.plugins.leofts'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leofts.py", line 1, in <module>
    import whoosh
ImportError: No module named whoosh
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:418: WARNING: autodoc: failed to import module u'leo.plugins.leomylyn'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leomylyn.py", line 31, in <module>
    from PyQt4.QtCore import *
ImportError: No module named PyQt4.QtCore
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:426: WARNING: autodoc: failed to import module u'leo.plugins.leoremote'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leoremote.py", line 35, in <module>
    from leo.external import lproto
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/external/lproto.py", line 16, in <module>
    from PyQt4 import QtCore, QtNetwork
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:434: WARNING: autodoc: failed to import module u'leo.plugins.leoscreen'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/leoscreen.py", line 147, in <module>
    import stickynotes
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/stickynotes.py", line 64, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/macros.py:docstring of leo.plugins.macros:49: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/mnplugins.py:docstring of leo.plugins.mnplugins:9: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/mod_http.py:docstring of leo.plugins.mod_http.leo_interface.split_leo_path:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/multifile.py:docstring of leo.plugins.multifile:25: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/multifile.py:docstring of leo.plugins.multifile:30: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/multifile.py:docstring of leo.plugins.multifile:31: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:562: WARNING: autodoc: failed to import module u'leo.plugins.nav_qt'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/nav_qt.py", line 30, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:570: WARNING: autodoc: failed to import module u'leo.plugins.nested_splitter'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/nested_splitter.py", line 19, in <module>
    from PyQt4 import QtGui, QtCore, Qt
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:594: WARNING: autodoc: failed to import module u'leo.plugins.notebook'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/notebook.py", line 29, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:642: WARNING: autodoc: failed to import module u'leo.plugins.pretty_print'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/pretty_print.py", line 28, in <module>
    oldPrettyPrinter = leoCommands.Commands.prettyPrinter
AttributeError: type object 'Commands' has no attribute 'prettyPrinter'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:650: WARNING: autodoc: failed to import module u'leo.plugins.projectwizard'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/projectwizard.py", line 26, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:658: WARNING: autodoc: failed to import module u'leo.plugins.qtGui'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/qtGui.py", line 33, in <module>
    import leo.plugins.baseNativeTree as baseNativeTree
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/baseNativeTree.py", line 19, in <module>
    import PyQt4.QtGui as QtGui
ImportError: No module named PyQt4.QtGui
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:666: WARNING: autodoc: failed to import module u'leo.plugins.qt_main'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/qt_main.py", line 10, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:674: WARNING: autodoc: failed to import module u'leo.plugins.qt_quicksearch'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/qt_quicksearch.py", line 10, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:690: WARNING: autodoc: failed to import module u'leo.plugins.quickMove'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/quickMove.py", line 127, in <module>
    if g.app.gui.guiName() == "qt":
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:698: WARNING: autodoc: failed to import module u'leo.plugins.quicksearch'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/quicksearch.py", line 67, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/rst3.py:docstring of leo.plugins.rst3.link_htmlparserClass:4: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/rst3.py:docstring of leo.plugins.rst3.link_htmlparserClass.handle_starttag:4: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:746: WARNING: autodoc: failed to import module u'leo.plugins.screen_capture'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/screen_capture.py", line 42, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:754: WARNING: autodoc: failed to import module u'leo.plugins.screencast'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/screencast.py", line 225, in <module>
    import PyQt4.QtCore as QtCore
ImportError: No module named PyQt4.QtCore
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:802: WARNING: autodoc: failed to import module u'leo.plugins.spydershell'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/spydershell.py", line 32, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:818: WARNING: autodoc: failed to import module u'leo.plugins.stickynotes'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/stickynotes.py", line 64, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:826: WARNING: autodoc: failed to import module u'leo.plugins.stickynotes_plus'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/stickynotes_plus.py", line 20, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:834: WARNING: autodoc: failed to import module u'leo.plugins.swing_gui'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/swing_gui.py", line 26, in <module>
    import javax.swing as swing
ImportError: No module named javax.swing
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:842: WARNING: autodoc: failed to import module u'leo.plugins.systray'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/systray.py", line 22, in <module>
    g.assertUi('qt')
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/core/leoGlobals.py", line 5196, in assertUi
    if not g.app.gui.guiName() == uitype:
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:866: WARNING: autodoc: failed to import module u'leo.plugins.threadutil'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/threadutil.py", line 6, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:882: WARNING: autodoc: failed to import module u'leo.plugins.todo'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/todo.py", line 61, in <module>
    if g.app.gui.guiName() == "qt":
AttributeError: 'NoneType' object has no attribute 'guiName'
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last:2: WARNING: Inline literal start-string without end-string.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last:6: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last_pretty:2: WARNING: Inline literal start-string without end-string.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last_pretty:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last_pretty:6: ERROR: Unexpected indentation.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last_pretty:6: WARNING: Inline literal start-string without end-string.
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/valuespace.py:docstring of leo.plugins.valuespace.vs_last_pretty:7: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:930: WARNING: autodoc: failed to import module u'leo.plugins.viewrendered'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/viewrendered.py", line 177, in <module>
    import leo.plugins.qtGui as qtGui
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/qtGui.py", line 33, in <module>
    import leo.plugins.baseNativeTree as baseNativeTree
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/baseNativeTree.py", line 19, in <module>
    import PyQt4.QtGui as QtGui
ImportError: No module named PyQt4.QtGui
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:962: WARNING: autodoc: failed to import module u'leo.plugins.wxGui'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/wxGui.py", line 62, in <module>
    import leo.plugins.baseNativeTree as baseNativeTree
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/baseNativeTree.py", line 19, in <module>
    import PyQt4.QtGui as QtGui
ImportError: No module named PyQt4.QtGui
/home/PeckJ/repos/leo-editor-docs/leo-editor/sphinx-docs/leo.plugins.rst:978: WARNING: autodoc: failed to import module u'leo.plugins.xml_edit'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 326, in import_object
    __import__(self.modname)
  File "/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/xml_edit.py", line 103, in <module>
    from lxml import etree
ImportError: No module named lxml
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/plugins_menu.py:docstring of leo.plugins.plugins_menu.PlugIn.getNiceName:3: ERROR: Unknown target name: "at".
/home/PeckJ/repos/leo-editor-docs/leo-editor/leo/plugins/plugins_menu.py:docstring of leo.plugins.plugins_menu.PlugIn.getNiceName:3: ERROR: Unknown target name: "mod".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 14%] index
writing output... [ 28%] leo
writing output... [ 42%] leo.core
writing output... [ 57%] leo.external
writing output... [ 71%] leo.external.concurrent
writing output... [ 85%] leo.external.concurrent.futures
writing output... [100%] leo.plugins

writing additional files... (117 module code pages) _modules/index
 genindex py-modindex search
copying static files... done
dumping search index... done
dumping object inventory... done
build succeeded, 112 warnings.

Build finished. The HTML pages are in _build/html.
